version: '3'
services:  
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432" 
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sendit
      - POSTGRES_PASSWORD=sendit
      - POSTGRES_DB=sendit

volumes:
  db:
    driver: local